import { StudioTheme } from '../types/studio';

export const LIGHT_THEME: StudioTheme = {
  name: 'light',
  colors: {
    background: '#ffffff',
    surface: '#f8f9fa',
    primary: '#2563eb',
    secondary: '#64748b',
    accent: '#0ea5e9',
    text: '#1e293b',
    textSecondary: '#64748b',
    border: '#e2e8f0',
    grid: '#f1f5f9',
    selection: '#3b82f6',
    error: '#ef4444',
    warning: '#f59e0b',
    success: '#10b981',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
  },
};

export const DARK_THEME: StudioTheme = {
  name: 'dark',
  colors: {
    background: '#0f172a',
    surface: '#1e293b',
    primary: '#3b82f6',
    secondary: '#64748b',
    accent: '#06b6d4',
    text: '#f8fafc',
    textSecondary: '#cbd5e1',
    border: '#334155',
    grid: '#1e293b',
    selection: '#3b82f6',
    error: '#f87171',
    warning: '#fbbf24',
    success: '#34d399',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.3)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.3), 0 2px 4px -2px rgb(0 0 0 / 0.3)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.3), 0 4px 6px -4px rgb(0 0 0 / 0.3)',
  },
};

export const DEFAULT_CANVAS_CONFIG = {
  width: 1200,
  height: 800,
  backgroundColor: 0xffffff,
  gridEnabled: true,
  gridSize: 20,
  gridColor: 0xf1f5f9,
  snapToGrid: true,
  showRulers: false,
};

export const NODE_CATEGORIES = [
  {
    id: 'flow-control',
    name: 'Flow Control',
    icon: '🔀',
    color: '#3b82f6',
    types: ['start', 'end', 'decision', 'condition', 'switch', 'loop', 'parallel', 'merge', 'wait', 'delay', 'timer', 'split']
  },
  {
    id: 'data-processing',
    name: 'Data Processing',
    icon: '📊',
    color: '#f59e0b',
    types: ['data-transform', 'filter', 'sort', 'aggregate', 'join', 'split-data', 'data-validation']
  },
  {
    id: 'integration',
    name: 'Integration & API',
    icon: '�',
    color: '#10b981',
    types: ['api-call', 'webhook', 'http-request', 'graphql', 'websocket', 'rest-api']
  },
  {
    id: 'communication',
    name: 'Communication',
    icon: '📧',
    color: '#8b5cf6',
    types: ['email', 'sms', 'notification', 'slack', 'teams', 'webhook-response']
  },
  {
    id: 'ai-ml',
    name: 'AI/ML',
    icon: '🤖',
    color: '#06b6d4',
    types: ['ai-model', 'text-generation', 'image-processing', 'classification', 'sentiment-analysis']
  },
  {
    id: 'database-storage',
    name: 'Database & Storage',
    icon: '🗄️',
    color: '#ec4899',
    types: ['database', 'file-system', 's3-storage', 'redis', 'mongodb', 'postgresql']
  },
  {
    id: 'business-logic',
    name: 'Business Logic',
    icon: '⚙️',
    color: '#84cc16',
    types: ['action', 'script', 'function-call', 'business-rule', 'validation-rule']
  },
  {
    id: 'advanced',
    name: 'Advanced',
    icon: '�',
    color: '#f97316',
    types: ['custom', 'sub-workflow', 'error-handler']
  }
];

export const DEFAULT_NODE_STYLES = {
  // Flow Control
  start: {
    backgroundColor: 0x10b981,
    borderColor: 0x059669,
    borderWidth: 2,
    borderRadius: 20,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'bold',
    shadow: true,
    opacity: 1,
  },
  end: {
    backgroundColor: 0xef4444,
    borderColor: 0xdc2626,
    borderWidth: 2,
    borderRadius: 20,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'bold',
    shadow: true,
    opacity: 1,
  },
  decision: {
    backgroundColor: 0xf59e0b,
    borderColor: 0xd97706,
    borderWidth: 2,
    borderRadius: 4,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  condition: {
    backgroundColor: 0x3b82f6,
    borderColor: 0x2563eb,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  switch: {
    backgroundColor: 0x8b5cf6,
    borderColor: 0x7c3aed,
    borderWidth: 2,
    borderRadius: 12,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  loop: {
    backgroundColor: 0x06b6d4,
    borderColor: 0x0891b2,
    borderWidth: 2,
    borderRadius: 16,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  parallel: {
    backgroundColor: 0x84cc16,
    borderColor: 0x65a30d,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  merge: {
    backgroundColor: 0xf97316,
    borderColor: 0xea580c,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  wait: {
    backgroundColor: 0x64748b,
    borderColor: 0x475569,
    borderWidth: 2,
    borderRadius: 20,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  delay: {
    backgroundColor: 0x64748b,
    borderColor: 0x475569,
    borderWidth: 2,
    borderRadius: 16,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  timer: {
    backgroundColor: 0x64748b,
    borderColor: 0x475569,
    borderWidth: 2,
    borderRadius: 12,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  split: {
    backgroundColor: 0x64748b,
    borderColor: 0x475569,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },

  // Data Processing
  'data-transform': {
    backgroundColor: 0xf59e0b,
    borderColor: 0xd97706,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  filter: {
    backgroundColor: 0x3b82f6,
    borderColor: 0x2563eb,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  sort: {
    backgroundColor: 0x10b981,
    borderColor: 0x059669,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  aggregate: {
    backgroundColor: 0x8b5cf6,
    borderColor: 0x7c3aed,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  join: {
    backgroundColor: 0x06b6d4,
    borderColor: 0x0891b2,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'split-data': {
    backgroundColor: 0xf97316,
    borderColor: 0xea580c,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'data-validation': {
    backgroundColor: 0xec4899,
    borderColor: 0xdb2777,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },

  // Integration & API
  'api-call': {
    backgroundColor: 0x10b981,
    borderColor: 0x059669,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  webhook: {
    backgroundColor: 0x3b82f6,
    borderColor: 0x2563eb,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'http-request': {
    backgroundColor: 0x8b5cf6,
    borderColor: 0x7c3aed,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  graphql: {
    backgroundColor: 0xf97316,
    borderColor: 0xea580c,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  websocket: {
    backgroundColor: 0x06b6d4,
    borderColor: 0x0891b2,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'rest-api': {
    backgroundColor: 0x84cc16,
    borderColor: 0x65a30d,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },

  // Communication
  email: {
    backgroundColor: 0x3b82f6,
    borderColor: 0x2563eb,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  sms: {
    backgroundColor: 0x10b981,
    borderColor: 0x059669,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  notification: {
    backgroundColor: 0xf59e0b,
    borderColor: 0xd97706,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  slack: {
    backgroundColor: 0x8b5cf6,
    borderColor: 0x7c3aed,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  teams: {
    backgroundColor: 0x06b6d4,
    borderColor: 0x0891b2,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'webhook-response': {
    backgroundColor: 0xf97316,
    borderColor: 0xea580c,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },

  // AI/ML
  'ai-model': {
    backgroundColor: 0x8b5cf6,
    borderColor: 0x7c3aed,
    borderWidth: 2,
    borderRadius: 12,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'text-generation': {
    backgroundColor: 0x06b6d4,
    borderColor: 0x0891b2,
    borderWidth: 2,
    borderRadius: 12,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'image-processing': {
    backgroundColor: 0xf97316,
    borderColor: 0xea580c,
    borderWidth: 2,
    borderRadius: 12,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  classification: {
    backgroundColor: 0x84cc16,
    borderColor: 0x65a30d,
    borderWidth: 2,
    borderRadius: 12,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'sentiment-analysis': {
    backgroundColor: 0xec4899,
    borderColor: 0xdb2777,
    borderWidth: 2,
    borderRadius: 12,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },

  // Database & Storage
  database: {
    backgroundColor: 0x64748b,
    borderColor: 0x475569,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'file-system': {
    backgroundColor: 0x3b82f6,
    borderColor: 0x2563eb,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  's3-storage': {
    backgroundColor: 0xf59e0b,
    borderColor: 0xd97706,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  redis: {
    backgroundColor: 0xdc2626,
    borderColor: 0xb91c1c,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  mongodb: {
    backgroundColor: 0x10b981,
    borderColor: 0x059669,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  postgresql: {
    backgroundColor: 0x8b5cf6,
    borderColor: 0x7c3aed,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },

  // Business Logic
  action: {
    backgroundColor: 0x3b82f6,
    borderColor: 0x2563eb,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  script: {
    backgroundColor: 0x64748b,
    borderColor: 0x475569,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'function-call': {
    backgroundColor: 0x06b6d4,
    borderColor: 0x0891b2,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'business-rule': {
    backgroundColor: 0x84cc16,
    borderColor: 0x65a30d,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'validation-rule': {
    backgroundColor: 0xec4899,
    borderColor: 0xdb2777,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },

  // Advanced
  custom: {
    backgroundColor: 0x64748b,
    borderColor: 0x475569,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'sub-workflow': {
    backgroundColor: 0xf97316,
    borderColor: 0xea580c,
    borderWidth: 2,
    borderRadius: 12,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
  'error-handler': {
    backgroundColor: 0xef4444,
    borderColor: 0xdc2626,
    borderWidth: 2,
    borderRadius: 8,
    textColor: 0xffffff,
    fontSize: 14,
    fontWeight: 'normal',
    shadow: true,
    opacity: 1,
  },
};
